/// AI Agent 相关命令

use serde::{Deserialize, Serialize};
use tauri::State;
use tracing::info;

use crate::ai::agent::{AgentConfig, ReactAgent};
use crate::ai::mcp::{McpClient, McpConfig};
use crate::ai::sandbox::{Sandbox, SandboxConfig};
use crate::error::{AppError, AppResult};
use crate::state::AppState;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AgentRequest {
    pub task: String,
    pub max_iterations: Option<usize>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AgentResponse {
    pub success: bool,
    pub answer: String,
    pub trace: AgentTraceSummary,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AgentTraceSummary {
    pub iterations: usize,
    pub tools_used: Vec<String>,
}

/// 执行 Agent 任务
#[tauri::command]
pub async fn agent_execute(
    app_state: State<'_, AppState>,
    request: AgentRequest,
) -> AppResult<AgentResponse> {
    info!(task = %request.task, "Executing agent task");

    // 初始化 Sandbox
    let sandbox_config = SandboxConfig::new(&app_state.app_data_dir);
    let sandbox = Sandbox::new(sandbox_config);

    // 初始化 MCP Client
    let mcp_config = McpConfig::new("http://localhost:3000".into());
    let mut mcp_client = McpClient::new(mcp_config);
    mcp_client.initialize().await?;

    // 创建并运行 Agent
    let agent_config = AgentConfig {
        max_iterations: request.max_iterations.unwrap_or(10),
        temperature: 0.7,
    };

    let mut agent = ReactAgent::new(agent_config, mcp_client, sandbox);
    let trace = agent.run(&request.task).await?;

    // 构建响应
    let tools_used: Vec<String> = trace.thoughts.iter()
        .filter_map(|t| t.action.as_ref().map(|a| a.tool_name.clone()))
        .collect();

    Ok(AgentResponse {
        success: true,
        answer: trace.final_answer.unwrap_or_default(),
        trace: AgentTraceSummary {
            iterations: trace.thoughts.len(),
            tools_used,
        },
    })
}

/// 配置 Qwen 模型
#[tauri::command]
pub async fn configure_qwen_model(
    api_key: String,
    model_id: String,
    base_url: Option<String>,
) -> AppResult<()> {
    info!(model = %model_id, "Configuring Qwen model");

    // TODO: 保存模型配置到数据库或配置文件
    // 这里先提供简单的日志记录
    
    info!(
        api_key_len = api_key.len(),
        base_url = base_url.as_deref().unwrap_or("default"),
        "Qwen model configuration received"
    );

    Ok(())
}

/// 生成网页摘要
#[tauri::command]
pub async fn generate_page_summary(
    app_state: State<'_, AppState>,
    url: String,
    content: String,
) -> AppResult<String> {
    info!(url = %url, "Generating page summary");

    // TODO: 调用 LLM 生成摘要
    // 这里先提供简单的模拟实现
    
    let summary = format!(
        "Summary of {}\n\nThis page contains information about the topic. [Full summary would be generated by LLM]",
        url
    );

    // 保存到 Sandbox
    let sandbox_config = SandboxConfig::new(&app_state.app_data_dir);
    let sandbox = Sandbox::new(sandbox_config);
    sandbox.save_summary(&url, &summary)?;

    Ok(summary)
}

/// 提取记忆
#[tauri::command]
pub async fn extract_memory(
    app_state: State<'_, AppState>,
    user_input: String,
) -> AppResult<Vec<(String, String)>> {
    info!("Extracting memories from user input");

    // TODO: 调用 LLM 提取关键信息作为记忆
    // 这里先提供模拟实现
    
    let memories: Vec<(String, String)> = vec![
        ("user_preference".to_string(), "User prefers concise answers".to_string()),
        ("recent_interest".to_string(), "User is interested in AI technology".to_string()),
    ];

    // 保存到 Sandbox
    let sandbox_config = SandboxConfig::new(&app_state.app_data_dir);
    let sandbox = Sandbox::new(sandbox_config);
    
    for (key, value) in &memories {
        sandbox.save_memory(key, value, "extracted")?;
    }

    Ok(memories)
}
